CONFIG:
  projectPath: /users/cuffe002/desktop/projects/mamba/mamba_edl/demo_business_data
  mode: linkage
  target_table: null
  ignore_duplicate_ids: false
  model_only: false
  debugmode: false
  database_creation_mode: true
  create_db_chunksize: 100000
  chatty_logger: false
  log_file_name: mamba_log
  numWorkers: 2
  imputation_method: No Imputation
  sql_flavor: sqlite
  db_name: sqlite_db.db
  data1_name: data1
  data2_name: data2
  prediction: true
  match_threshold: 0.5
  scoringcriteria: f1
  matched_pairs_table_name: matched_pairs
  clerical_review_candidates: false
  use_mamba_models: true
  use_custom_model: false
  custom_model_name: ''
  saved_model: ''
  use_ada: true
  use_rf: false
  rf_jobs: 1
  use_logit: false
  feature_elimination_mode: false
  training_data_name: training_data.csv
  saved_model_target: my_saved_model.joblib
  used_fuzzy_metrics:
    - feb.charhistogram
    - feb.editdist
    - feb.jaro
  custom_selection_statement:
    left: ''
    right: ''
  debug_blocks:
    - block_order: '1'
      block_variable_information:
        - variable: zip3
          value: '223'
blocks:
  - order: 1
    block_name: zip3
    left: zip3
    right: zip3
    variable_filter_info:
      left: zip5
      right: zip5
      match_type: exact
      test: '=='
var_types:
  - variable_name: name
    custom_variable_name: ''
    match_type:
      - fuzzy
    left: name
    right: name
